%% Define the rules of the fuzzy logic

Fuzzy_Rules = ...
    {@zero, @zero, @PO1, @PO2, @one, @PL;...
     @zero, @zero, @PO1, @ZE2, @one, @PM;...
     @zero, @zero, @PO1, @NE2, @one, @ZE;...
     @zero, @zero, @ZE1, @PO2, @one, @PS;...
     @zero, @zero, @ZE1, @ZE2, @one, @ZE;...
     @zero, @zero, @ZE1, @NE2, @one, @NS;...
     @zero, @zero, @NE1, @PO2, @one, @ZE;...
     @zero, @zero, @NE1, @ZE2, @one, @NM;...
     @zero, @zero, @NE1, @NE2, @one, @NL;...
     @PO3, @PO4, @VS1, @VS2, @one, @PS;...
     @PO3, @PS4, @VS1, @VS2, @one, @PVS;...
     @NE3, @NE4, @VS1, @VS2, @one, @NS;...
     @NE3, @NS4, @VS1, @VS2, @one, @NVS};

% Fuzzy_Rules = ...
%     {@PO1, @PO2, @zero, @zero, @one, @PL;...
%      @PO1, @ZE2, @zero, @zero, @one, @PM;...
%      @PO1, @NE2, @zero, @zero, @one, @ZE;...
%      @ZE1, @PO2, @zero, @zero, @one, @PS; ...
%      @ZE1, @ZE2, @zero, @zero, @one, @ZE;...
%      @ZE1, @NE2, @zero, @zero, @one, @NS;...
%      @NE1, @PO2, @zero, @zero, @one, @ZE;...
%      @NE1, @ZE2, @zero, @zero, @one, @NM;...
%      @NE1, @NE2, @zero, @zero, @one, @NL;...
%      @VS1, @VS2, @PO3, @PO4,  @one, @PS;...
%      @VS1, @VS2, @PO3, @PS4,  @one, @PVS;...
%      @VS1, @VS2, @NE3, @NE4,  @one, @NS;...
%      @VS1, @VS2, @NE3, @NS4,  @one, @NVS};
